# Generated by Django 5.0.2 on 2024-03-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Horses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=255)),
                ('horse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horses.horse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
