# Generated by Django 5.0.2 on 2024-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horse_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse_images',
            name='image_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
