# Generated by Django 5.0.2 on 2024-03-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='Password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='Username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
