# Generated by Django 5.0.2 on 2024-03-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('horse_name', models.CharField(max_length=100)),
                ('horse_gender', models.CharField(max_length=100)),
                ('horse_was_born', models.DateTimeField()),
                ('horse_weight', models.IntegerField()),
                ('horse_height_at_withers', models.FloatField()),
                ('start_price', models.IntegerField()),
                ('bid_step', models.IntegerField()),
                ('horse_highest_sport_result', models.CharField(max_length=255)),
                ('actual_price', models.IntegerField()),
                ('bid_start', models.DateTimeField()),
                ('breeder_id', models.BigIntegerField()),
                ('sport_specification_id', models.BigIntegerField()),
                ('sale_state', models.BigIntegerField()),
                ('bidder_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
